services:
  rob-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-env
      args:
        DOWNLOAD_WEIGHTS: "false"  
    container_name: rob-app-container
    volumes:
      - ./:/pre-rob
      - /usr/lib/wsl:/usr/lib/wsl:ro
      - ./rob-app/input:/input
      - ./rob-app/output:/output
    working_dir: /pre-rob/rob-app
    ports:
      - "5679:5678"  # Debugging port
    environment:
      LD_LIBRARY_PATH: "/usr/lib/wsl/lib:${LD_LIBRARY_PATH:-}"
    gpus: all
    stdin_open: true
    tty: true
    entrypoint:
      - /bin/bash
      - -c
      - |
        python -m debugpy --listen 0.0.0.0:5678 --wait-for-client \
               rob.py -i /input/input.csv -o /output/output.csv
